# Generated by Django 6.0.2 on 2026-02-05 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('INTERN', 'Intern'), ('JUNIOR_ANALYST', 'Junior Analyst'), ('TEAM_LEADER', 'Team Leader'), ('MANAGER', 'Manager'), ('CEO', 'CEO')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.team')),
            ],
            options={
                'unique_together': {('team', 'role')},
            },
        ),
    ]
