# Generated by Django 6.0.2 on 2026-02-06 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exit_code', models.UUIDField(blank=True, null=True, unique=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FORCED_EXIT', 'Forced Exit'), ('INVALIDATED', 'Invalidated')], default='ACTIVE', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
            options={
                'unique_together': {('team', 'zone')},
            },
        ),
    ]
