# Generated by Django 6.0.2 on 2026-02-06 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_zoneattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoneattempt',
            name='exit_code',
        ),
        migrations.AlterField(
            model_name='zoneattempt',
            name='entry_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='zoneattempt',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FORCED_EXIT', 'Forced Exit')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='ZoneAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_code', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
            options={
                'unique_together': {('team', 'zone')},
            },
        ),
    ]
