# Generated by Django 6.0.2 on 2026-02-06 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_zoneattempt_exit_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone1', models.IntegerField(default=0)),
                ('zone2', models.IntegerField(default=0)),
                ('zone3', models.IntegerField(default=0)),
                ('zone4', models.IntegerField(default=0)),
                ('zone5', models.IntegerField(default=0)),
                ('zone6', models.IntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='app.team')),
            ],
        ),
    ]
