# Generated by Django 6.0.2 on 2026-02-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zoneaccess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='zoneaccess',
            name='team',
        ),
        migrations.RemoveField(
            model_name='zoneaccess',
            name='zone',
        ),
        migrations.AlterUniqueTogether(
            name='zoneattempt',
            unique_together={('player', 'zone')},
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='zoneattempt',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_attempts', to='app.player'),
        ),
        migrations.AlterField(
            model_name='zoneattempt',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_attempts', to='app.team'),
        ),
        migrations.AlterField(
            model_name='zoneattempt',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='app.zone'),
        ),
        migrations.CreateModel(
            name='ZoneAttemptAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_code', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_access_codes', to='app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_access_codes', to='app.team')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='app.zone')),
            ],
        ),
        migrations.AddField(
            model_name='zoneattempt',
            name='access',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='attempt', to='app.zoneattemptaccess'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='zoneattempt',
            index=models.Index(fields=['zone', 'status'], name='app_zoneatt_zone_id_7ed40a_idx'),
        ),
        migrations.AddIndex(
            model_name='zoneattempt',
            index=models.Index(fields=['player', 'status'], name='app_zoneatt_player__c0508f_idx'),
        ),
        migrations.DeleteModel(
            name='ZoneAccess',
        ),
        migrations.RemoveField(
            model_name='zoneattempt',
            name='entry_code',
        ),
        migrations.RemoveField(
            model_name='zoneattempt',
            name='score',
        ),
        migrations.AddIndex(
            model_name='zoneattemptaccess',
            index=models.Index(fields=['attempt_code'], name='app_zoneatt_attempt_9aab60_idx'),
        ),
        migrations.AddIndex(
            model_name='zoneattemptaccess',
            index=models.Index(fields=['zone'], name='app_zoneatt_zone_id_31b264_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zoneattemptaccess',
            unique_together={('player', 'zone')},
        ),
    ]
