# Generated by Django 6.0.2 on 2026-02-08 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_zoneaccess_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INTERN', 'Intern'), ('JUNIOR_ANALYST', 'Junior Analyst'), ('TEAM_LEADER', 'Team Leader'), ('MANAGER', 'Manager'), ('CEO', 'CEO')], max_length=20)),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('CODE', 'Code'), ('MCQ', 'MCQ')], max_length=10)),
                ('payload', models.TextField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app.zone')),
            ],
        ),
    ]
