# Generated by Django 6.0.2 on 2026-02-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_zonecontent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zonecontent',
            unique_together={('zone', 'role')},
        ),
        migrations.AddField(
            model_name='zonecontent',
            name='content',
            field=models.TextField(default=2, help_text='HTML / Markdown / plain text rendered inside the zone'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='zonecontent',
            index=models.Index(fields=['zone', 'role'], name='app_zonecon_zone_id_39d44c_idx'),
        ),
        migrations.RemoveField(
            model_name='zonecontent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='zonecontent',
            name='payload',
        ),
    ]
