# Generated by Django 4.2 on 2026-02-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_zonecontent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonecontent',
            name='exit_code',
            field=models.CharField(blank=True, help_text='Code required to exit/submit this zone', max_length=50, null=True),
        ),
    ]
