# Generated by Django 6.0.2 on 2026-02-11 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_zonecontent_exit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='credit',
            field=models.IntegerField(default=0, help_text='Standalone credits used for tie-breaking or advantages.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
